[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
AbstractGPsMakie = "7834405d-1089-4985-bd30-732a30b92057"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ParameterHandling = "2412ca09-6db7-441c-8e3a-88d5709968c5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AbstractGPs = "0.5"
AbstractGPsMakie = "0.2"
CairoMakie = "0.7, 0.8, 0.9, 0.10, 0.11, 0.12"
KernelFunctions = "0.10"
Literate = "2"
Optim = "1"
ParameterHandling = "0.4, 0.5"
Zygote = "0.6"
