[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
AdvancedHMC = "0bf59076-c3b1-5ca4-86bd-e02cd72cde3d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
EllipticalSliceSampling = "cad2338a-1db2-11e9-3401-43bc07c9ede2"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
AbstractGPs = "0.5"
AdvancedHMC = "0.4"
Distributions = "0.25"
DynamicHMC = "3.3"
EllipticalSliceSampling = "1"
FillArrays = "0.13"
ForwardDiff = "0.10"
Literate = "2.5"
LogDensityProblems = "2"
LogDensityProblemsAD = "1"
Optim = "1"
Plots = "1"
StatsFuns = "1"
