[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
AbstractGPs = "0.4, 0.5, 0.6"
Documenter = "0.27"
